# Generated by Django 5.1.7 on 2025-06-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("sous_titre", models.CharField(max_length=255)),
                ("corps", models.TextField()),
                (
                    "image_principale",
                    models.ImageField(blank=True, null=True, upload_to="blog/main/"),
                ),
                (
                    "images_secondaires",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/secondary/"
                    ),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="blog.categorie",
                    ),
                ),
            ],
        ),
    ]
