# Generated by Django 5.1.7 on 2025-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                ("quartier", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="agences/images/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
